import type { User, Report, Notification } from "./types";

// Requirement 15.1: 4 Student users and 1 Admin user
export const mockUsers: User[] = [
  {
    id: "user-student-1",
    name: "Alex Rivera",
    email: "student1@csu.fullerton.edu",
    passwordHash: "password123",
    role: "student",
    avatar: "https://picsum.photos/seed/avatar1/100/100",
    isVerified: true,
    mfaEnabled: false,
    failedLoginAttempts: 0,
    lockedUntil: null,
    notificationPrefs: {
      emailEnabled: true,
      inAppEnabled: true,
      categories: { safety: true, maintenance: true, harassment: true, lostAndFound: true, other: true },
    },
    language: "en",
    publicProfile: true,
    locationPermission: true,
    createdAt: "2025-01-10T08:00:00.000Z",
  },
  {
    id: "user-student-2",
    name: "Jordan Kim",
    email: "student2@csu.fullerton.edu",
    passwordHash: "password123",
    role: "student",
    avatar: "https://picsum.photos/seed/avatar2/100/100",
    isVerified: true,
    mfaEnabled: false,
    failedLoginAttempts: 0,
    lockedUntil: null,
    notificationPrefs: {
      emailEnabled: true,
      inAppEnabled: true,
      categories: { safety: true, maintenance: true, harassment: true, lostAndFound: true, other: true },
    },
    language: "en",
    publicProfile: true,
    locationPermission: true,
    createdAt: "2025-01-12T10:30:00.000Z",
  },
  {
    id: "user-student-3",
    name: "Sam Patel",
    email: "student3@csu.fullerton.edu",
    passwordHash: "password123",
    role: "student",
    avatar: "https://picsum.photos/seed/avatar3/100/100",
    isVerified: true,
    mfaEnabled: false,
    failedLoginAttempts: 0,
    lockedUntil: null,
    notificationPrefs: {
      emailEnabled: false,
      inAppEnabled: true,
      categories: { safety: true, maintenance: false, harassment: true, lostAndFound: false, other: false },
    },
    language: "es",
    publicProfile: false,
    locationPermission: true,
    createdAt: "2025-01-15T14:00:00.000Z",
  },
  {
    id: "user-student-4",
    name: "Taylor Nguyen",
    email: "student4@csu.fullerton.edu",
    passwordHash: "password123",
    role: "student",
    avatar: "https://picsum.photos/seed/avatar4/100/100",
    isVerified: false,
    mfaEnabled: false,
    failedLoginAttempts: 0,
    lockedUntil: null,
    notificationPrefs: {
      emailEnabled: true,
      inAppEnabled: true,
      categories: { safety: true, maintenance: true, harassment: true, lostAndFound: true, other: true },
    },
    language: "en",
    publicProfile: true,
    locationPermission: false,
    createdAt: "2025-01-18T09:15:00.000Z",
  },
  {
    id: "user-admin-1",
    name: "Dr. Campus Admin",
    email: "admin@csu.fullerton.edu",
    passwordHash: "admin123",
    role: "admin",
    avatar: "https://picsum.photos/seed/admin/100/100",
    isVerified: true,
    mfaEnabled: false,
    failedLoginAttempts: 0,
    lockedUntil: null,
    notificationPrefs: {
      emailEnabled: true,
      inAppEnabled: true,
      categories: { safety: true, maintenance: true, harassment: true, lostAndFound: true, other: true },
    },
    language: "en",
    publicProfile: true,
    locationPermission: true,
    createdAt: "2025-01-01T00:00:00.000Z",
  },
];

// Requirement 15.2: 10 reports at CSUF campus coordinates (SR-021)
// Coordinates match the illustrated campus map and aerial map
// 8 Open, 1 In Progress, 1 Resolved — at least 3 High, 3 Medium, 3 Low severity
export const mockReports: Report[] = [
  {
    id: "report-1",
    title: "Broken streetlight near Pollak Library",
    description: "The streetlight on the east side of Pollak Library has been out for over a week. Very dark at night and feels unsafe walking to the parking structure.",
    category: "Safety",
    severity: "High",
    status: "Open",
    location: { lat: 33.8820, lng: -117.8850, areaName: "Pollak Library" },
    photos: [
      { id: "photo-1a", url: "https://picsum.photos/seed/report1/400/300", fileType: "image/jpeg", uploadedAt: "2025-01-20T18:30:00.000Z" },
    ],
    isAnonymous: false,
    authorId: "user-student-1",
    upvotedBy: ["user-student-2", "user-student-3", "user-student-4"],
    submittedAt: "2025-01-20T18:30:00.000Z",
    resolvedAt: null,
    resolvedBy: null,
    resolutionNotes: null,
  },
  {
    id: "report-2",
    title: "Water leak in Titan Student Union restroom",
    description: "There is a persistent water leak in the second-floor restroom at the Titan Student Union. The floor is slippery and could cause someone to fall.",
    category: "Maintenance",
    severity: "Medium",
    status: "Open",
    location: { lat: 33.8812, lng: -117.8859, areaName: "Titan Student Union" },
    photos: [
      { id: "photo-2a", url: "https://picsum.photos/seed/report2/400/300", fileType: "image/jpeg", uploadedAt: "2025-01-21T09:00:00.000Z" },
      { id: "photo-2b", url: "https://picsum.photos/seed/report2b/400/300", fileType: "image/png", uploadedAt: "2025-01-21T09:01:00.000Z" },
    ],
    isAnonymous: false,
    authorId: "user-student-2",
    upvotedBy: ["user-student-1", "user-student-3"],
    submittedAt: "2025-01-21T09:00:00.000Z",
    resolvedAt: null,
    resolvedBy: null,
    resolutionNotes: null,
  },
  {
    id: "report-3",
    title: "Suspicious individual near Langsdorf Hall",
    description: "An unidentified person has been loitering near the Langsdorf Hall entrance for several hours, approaching students and asking for personal information.",
    category: "Safety",
    severity: "Critical",
    status: "Open",
    location: { lat: 33.8803, lng: -117.8846, areaName: "Langsdorf Hall" },
    photos: [],
    isAnonymous: true,
    authorId: "user-student-3",
    upvotedBy: ["user-student-1", "user-student-2", "user-student-4"],
    submittedAt: "2025-01-22T14:15:00.000Z",
    resolvedAt: null,
    resolvedBy: null,
    resolutionNotes: null,
  },
  {
    id: "report-4",
    title: "Lost backpack at McCarthy Hall",
    description: "I left my black North Face backpack in room 414 of McCarthy Hall after my 2pm class. It has a laptop and textbooks inside.",
    category: "Lost & Found",
    severity: "Low",
    status: "Open",
    location: { lat: 33.8798, lng: -117.8863, areaName: "McCarthy Hall" },
    photos: [
      { id: "photo-4a", url: "https://picsum.photos/seed/report4/400/300", fileType: "image/jpeg", uploadedAt: "2025-01-22T16:00:00.000Z" },
    ],
    isAnonymous: false,
    authorId: "user-student-1",
    upvotedBy: [],
    submittedAt: "2025-01-22T16:00:00.000Z",
    resolvedAt: null,
    resolvedBy: null,
    resolutionNotes: null,
  },
  {
    id: "report-5",
    title: "Elevator malfunction in Mihaylo Hall",
    description: "The main elevator in Mihaylo Hall has been making grinding noises and getting stuck between floors. Multiple students have been trapped briefly.",
    category: "Maintenance",
    severity: "High",
    status: "In Progress",
    location: { lat: 33.8786, lng: -117.8838, areaName: "Mihaylo Hall" },
    photos: [
      { id: "photo-5a", url: "https://picsum.photos/seed/report5/400/300", fileType: "image/png", uploadedAt: "2025-01-19T11:00:00.000Z" },
    ],
    isAnonymous: false,
    authorId: "user-student-2",
    upvotedBy: ["user-student-1", "user-student-3", "user-student-4"],
    submittedAt: "2025-01-19T11:00:00.000Z",
    resolvedAt: null,
    resolvedBy: null,
    resolutionNotes: null,
  },
  {
    id: "report-6",
    title: "Harassment incident at Student Rec Center",
    description: "A student reported verbal harassment from another individual near the Student Rec Center around 9pm. The area was poorly lit.",
    category: "Harassment",
    severity: "High",
    status: "Open",
    location: { lat: 33.8844, lng: -117.8876, areaName: "Student Rec Center" },
    photos: [],
    isAnonymous: true,
    authorId: "user-student-4",
    upvotedBy: ["user-student-1", "user-student-2"],
    submittedAt: "2025-01-23T21:30:00.000Z",
    resolvedAt: null,
    resolvedBy: null,
    resolutionNotes: null,
  },
  {
    id: "report-7",
    title: "Cracked sidewalk at Nutwood Parking Structure",
    description: "There is a large crack in the sidewalk at the Nutwood Parking Structure entrance. It is a tripping hazard, especially at night.",
    category: "Maintenance",
    severity: "Medium",
    status: "Open",
    location: { lat: 33.8805, lng: -117.8898, areaName: "Nutwood Parking" },
    photos: [
      { id: "photo-7a", url: "https://picsum.photos/seed/report7/400/300", fileType: "image/jpeg", uploadedAt: "2025-01-21T13:45:00.000Z" },
    ],
    isAnonymous: false,
    authorId: "user-student-3",
    upvotedBy: ["user-student-1"],
    submittedAt: "2025-01-21T13:45:00.000Z",
    resolvedAt: null,
    resolvedBy: null,
    resolutionNotes: null,
  },
  {
    id: "report-8",
    title: "Graffiti at State College Parking Structure",
    description: "Offensive graffiti was found on the south wall of the State College Parking Structure this morning. It needs to be cleaned up promptly.",
    category: "Other",
    severity: "Low",
    status: "Open",
    location: { lat: 33.8836, lng: -117.8829, areaName: "State College Parking" },
    photos: [
      { id: "photo-8a", url: "https://picsum.photos/seed/report8/400/300", fileType: "image/jpeg", uploadedAt: "2025-01-23T07:30:00.000Z" },
      { id: "photo-8b", url: "https://picsum.photos/seed/report8b/400/300", fileType: "image/png", uploadedAt: "2025-01-23T07:31:00.000Z" },
    ],
    isAnonymous: false,
    authorId: "user-student-1",
    upvotedBy: ["user-student-2"],
    submittedAt: "2025-01-23T07:30:00.000Z",
    resolvedAt: null,
    resolvedBy: null,
    resolutionNotes: null,
  },
  {
    id: "report-9",
    title: "Missing fire extinguisher in Engineering / CS Building",
    description: "The fire extinguisher on the third floor of the Engineering / CS Building near room 310 is missing from its case. This is a serious safety concern.",
    category: "Safety",
    severity: "Medium",
    status: "Open",
    location: { lat: 33.8833, lng: -117.8833, areaName: "Engineering / CS" },
    photos: [
      { id: "photo-9a", url: "https://picsum.photos/seed/report9/400/300", fileType: "image/jpeg", uploadedAt: "2025-01-24T10:00:00.000Z" },
    ],
    isAnonymous: false,
    authorId: "user-student-4",
    upvotedBy: ["user-student-1", "user-student-2", "user-student-3"],
    submittedAt: "2025-01-24T10:00:00.000Z",
    resolvedAt: null,
    resolvedBy: null,
    resolutionNotes: null,
  },
  {
    id: "report-10",
    title: "Pothole near Housing — Pine Tree",
    description: "A large pothole has formed near the entrance of the Housing Pine Tree area. Several bikes have hit it and it is getting worse with rain.",
    category: "Maintenance",
    severity: "Low",
    status: "Resolved",
    location: { lat: 33.8850, lng: -117.8805, areaName: "Housing — Pine Tree" },
    photos: [
      { id: "photo-10a", url: "https://picsum.photos/seed/report10/400/300", fileType: "image/jpeg", uploadedAt: "2025-01-15T08:00:00.000Z" },
    ],
    isAnonymous: false,
    authorId: "user-student-2",
    upvotedBy: ["user-student-1", "user-student-3"],
    submittedAt: "2025-01-15T08:00:00.000Z",
    resolvedAt: "2025-01-20T16:00:00.000Z",
    resolvedBy: "user-admin-1",
    resolutionNotes: "Pothole has been filled and the area repaved. Thank you for reporting.",
  },
];

// Requirement 15.3: 6 notifications with a mix of types and urgencies
export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "user-student-2",
    type: "report_resolved",
    urgency: "non_urgent",
    category: "Maintenance",
    header: "Your report has been resolved",
    body: "The pothole in Eastside Parking Lot has been repaired. Thank you for reporting this issue.",
    read: false,
    sentAt: "2025-01-20T16:05:00.000Z",
    reportId: "report-10",
  },
  {
    id: "notif-2",
    userId: "user-student-1",
    type: "urgent_alert",
    urgency: "urgent",
    category: "Safety",
    header: "Urgent safety alert near Engineering Building",
    body: "A suspicious individual has been reported near the Engineering Building. Please exercise caution in the area.",
    read: false,
    sentAt: "2025-01-22T14:20:00.000Z",
    reportId: "report-3",
  },
  {
    id: "notif-3",
    userId: "user-student-1",
    type: "new_report",
    urgency: "non_urgent",
    category: "Maintenance",
    header: "New report in your area",
    body: "A water leak has been reported at Pollak Library. Check the report for details.",
    read: true,
    sentAt: "2025-01-21T09:05:00.000Z",
    reportId: "report-2",
  },
  {
    id: "notif-4",
    userId: "user-student-3",
    type: "status_change",
    urgency: "non_urgent",
    category: "Maintenance",
    header: "Report status updated",
    body: "The elevator malfunction report at Langsdorf Hall has been updated to In Progress.",
    read: false,
    sentAt: "2025-01-23T10:00:00.000Z",
    reportId: "report-5",
  },
  {
    id: "notif-5",
    userId: "user-student-4",
    type: "urgent_alert",
    urgency: "urgent",
    category: "Harassment",
    header: "Safety advisory for Nutwood Parking Structure",
    body: "A harassment incident was reported at Nutwood Parking Structure. Campus security has been notified.",
    read: true,
    sentAt: "2025-01-23T22:00:00.000Z",
    reportId: "report-6",
  },
  {
    id: "notif-6",
    userId: "user-student-2",
    type: "new_report",
    urgency: "non_urgent",
    category: "Safety",
    header: "New safety report near Titan Hall",
    body: "A missing fire extinguisher has been reported on the third floor of Titan Hall.",
    read: false,
    sentAt: "2025-01-24T10:05:00.000Z",
    reportId: "report-9",
  },
];
